# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170921_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ematt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emsalary',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='atten',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Ematt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='salar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Emsalary'),
            preserve_default=False,
        ),
    ]
