# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170925_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ematt',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='emsalary',
            name='profile',
        ),
    ]
