# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170927_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ematt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
