# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170927_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_all',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
