# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_profile_work_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='leave',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('', '')], default='', max_length=8),
        ),
    ]
