# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171008_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leave',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('', '')], default='', max_length=8, null=True),
        ),
    ]
