# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171008_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='leave',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Denied', 'Denied'), ('', '')], default='', max_length=8, null=True),
        ),
    ]
