# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20171008_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='leave',
            new_name='status',
        ),
    ]
