# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20171008_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Denied', 'Denied')], default='', max_length=8, null=True),
        ),
    ]
