# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20171011_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
