# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20171015_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
